---
- name: Collect facts
  hosts: localhost
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

- name: Sync repositories and update world
  community.general.portage:
    package: '@world'
    update: true
    deep: true
    sync: true
